spring:
  liquibase:
    contexts: dev
    change-log: classpath:/db/db.changelog-oracle.xml
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/ORCLCDB
    username:
    password:
decorator:
  datasource:
    enabled: true
