export const columns = reactive({
  selection: { label: '选择列', visible: false },
  index: { label: '序号列', visible: false },
  id: { label: 'ID', visible: false },
  deptId: { label: '部门 ID', visible: false },
  avatar: { label: '头像', visible: true },
  username: { label: '用户名', visible: true },
  nickname: { label: '用户昵称', visible: true },
  deptName: { label: '部门名称', visible: true },
  gender: { label: '性别', visible: true },
  mobile: { label: '移动电话', visible: true },
  email: { label: '邮箱', visible: true },
  disabled: { label: '状态', visible: true },
  remark: { label: '备注', visible: false },
  createByName: { label: '创建者', visible: false },
  createTime: { label: '创建时间', visible: false },
  updateByName: { label: '更新者', visible: false },
  updateTime: { label: '更新时间', visible: false },
  operation: { label: '操作', visible: true },
});
