export const columns = ref([
  { key: 0, label: '选择列', visible: false },
  { key: 1, label: '序号', visible: false },
  { key: 2, label: 'ID', visible: false },
  { key: 3, label: '菜单标题', visible: true },
  { key: 4, label: '图标', visible: true },
  { key: 5, label: '菜单类型', visible: true },
  { key: 6, label: '状态', visible: true },
  { key: 7, label: '排序', visible: true },
  { key: 8, label: '权限字符', visible: true },
  { key: 9, label: '组件', visible: true },
  { key: 10, label: '路由名称', visible: false },
  { key: 11, label: '路由路径', visible: false },
  { key: 12, label: 'URL', visible: false },
  { key: 13, label: '创建者', visible: false },
  { key: 14, label: '创建时间', visible: false },
  { key: 15, label: '更新者', visible: false },
  { key: 16, label: '更新时间', visible: false },
  { key: 17, label: '操作', visible: true },
])
