export const columns = reactive({
  selection: { label: '选择列', visible: false },
  index: { label: '序号列', visible: false },
  id: { label: 'ID', visible: false },
  title: { label: '菜单标题', visible: true },
  icon: { label: '图标', visible: true },
  type: { label: '菜单类型', visible: true },
  disabled: { label: '状态', visible: true },
  seq: { label: '排序', visible: true },
  permission: { label: '权限字符', visible: true },
  component: { label: '组件', visible: true },
  routeName: { label: '路由名称', visible: false },
  routePath: { label: '路由路径', visible: false },
  url: { label: 'URL', visible: false },
  createByName: { label: '创建者', visible: false },
  createTime: { label: '创建时间', visible: false },
  updateByName: { label: '更新者', visible: false },
  updateTime: { label: '更新时间', visible: false },
  operation: { label: '操作', visible: true },
});
