<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">  
    <modelVersion>4.0.0</modelVersion>  
    <parent> 
        <groupId>org.springframework.boot</groupId>  
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.11</version>
        <relativePath/> 
    </parent>  
    <groupId>com.github.mengweijin</groupId>
    <artifactId>vita-parent</artifactId>
    <version>2.0.0-M4</version>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <description>vita-parent</description>
    <url>https://github.com/mengweijin/vita</url>
    <modules> 
        <module>vita-admin</module>
        <module>vita-framework</module>
    </modules>
    <properties>
        <vita.version>2.0.0-M4</vita.version>
        <java.version>17</java.version>  
        <maven.compiler.source>${java.version}</maven.compiler.source>  
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>  
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-cloud.version>2025.0.0</spring-cloud.version>
        <mybatis-plus.version>3.5.16</mybatis-plus.version>
        <hutool.version>7.0.0-M4</hutool.version>
        <sa-token.version>1.44.0</sa-token.version>
        <oshi.version>6.10.0</oshi.version>
        <zxing.version>3.5.4</zxing.version>
        <fesod-sheet.version>2.0.1-incubating</fesod-sheet.version>
        <ip2region.version>3.3.4</ip2region.version>
        <velocity.version>2.4.1</velocity.version>
        <mapstruct-plus.version>1.4.8</mapstruct-plus.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
        <p6spy-spring-boot-starter.version>1.12.1</p6spy-spring-boot-starter.version>
        <springdoc.version>2.8.14</springdoc.version>
        <maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
        <central-publishing-maven-plugin.version>0.9.0</central-publishing-maven-plugin.version>
    </properties>
    <profiles>
        <profile>
            <id>local</id>
            <properties>
                <!-- 环境标识，需要与配置文件的名称相对应 -->
                <profiles.active>local</profiles.active>
                <logging.level>debug</logging.level>
            </properties>
        </profile>
        <profile>
            <id>dev</id>
            <properties>
                <!-- 环境标识，需要与配置文件的名称相对应 -->
                <profiles.active>dev</profiles.active>
                <logging.level>debug</logging.level>
            </properties>
            <activation>
                <!-- 默认环境 -->
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>h2</id>
            <properties>
                <!-- 环境标识，需要与配置文件的名称相对应 -->
                <profiles.active>h2</profiles.active>
                <logging.level>debug</logging.level>
            </properties>
        </profile>
        <profile>
            <id>postgresql</id>
            <properties>
                <!-- 环境标识，需要与配置文件的名称相对应 -->
                <profiles.active>postgresql</profiles.active>
                <logging.level>debug</logging.level>
            </properties>
        </profile>
        <profile>
            <id>mysql</id>
            <properties>
                <!-- 环境标识，需要与配置文件的名称相对应 -->
                <profiles.active>mysql</profiles.active>
                <logging.level>debug</logging.level>
            </properties>
        </profile>
        <profile>
            <id>oracle</id>
            <properties>
                <!-- 环境标识，需要与配置文件的名称相对应 -->
                <profiles.active>oracle</profiles.active>
                <logging.level>debug</logging.level>
            </properties>
        </profile>
        <profile> 
            <id>prod</id>  
            <properties> 
                <profiles.active>prod</profiles.active>  
                <logging.level>info</logging.level>
            </properties> 
        </profile> 
    </profiles>  
    <dependencyManagement> 
        <dependencies>
            <dependency>
                <groupId>com.github.mengweijin</groupId>
                <artifactId>vita-admin</artifactId>
                <version>${vita.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.mengweijin</groupId>
                <artifactId>vita-framework</artifactId>
                <version>${vita.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-jsqlparser</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency> 
                <groupId>com.github.gavlyukovskiy</groupId>  
                <artifactId>p6spy-spring-boot-starter</artifactId>  
                <version>${p6spy-spring-boot-starter.version}</version> 
            </dependency>  
            <dependency> 
                <groupId>cn.dev33</groupId>  
                <artifactId>sa-token-spring-boot3-starter</artifactId>  
                <version>${sa-token.version}</version> 
            </dependency>
            <dependency> 
                <groupId>cn.hutool.v7</groupId>
                <artifactId>hutool-all</artifactId>  
                <version>${hutool.version}</version> 
            </dependency>
            <dependency> 
                <groupId>com.github.oshi</groupId>  
                <artifactId>oshi-core</artifactId>  
                <version>${oshi.version}</version> 
            </dependency>  
            <dependency> 
                <groupId>com.google.zxing</groupId>  
                <artifactId>core</artifactId>  
                <version>${zxing.version}</version> 
            </dependency>
            <dependency> 
                <groupId>org.lionsoul</groupId>  
                <artifactId>ip2region</artifactId>  
                <version>${ip2region.version}</version> 
            </dependency>
            <dependency>
                <groupId>org.apache.fesod</groupId>
                <artifactId>fesod-sheet</artifactId>
                <version>${fesod-sheet.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.velocity</groupId>
                <artifactId>velocity-engine-core</artifactId>
                <version>${velocity.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.linpeilie</groupId>
                <artifactId>mapstruct-plus-spring-boot-starter</artifactId>
                <version>${mapstruct-plus.version}</version>
            </dependency>
        </dependencies> 
    </dependencyManagement>  
    <!-- 开源许可证 -->  
    <licenses> 
        <license> 
            <name>The Apache Software License, Version 2.0</name>  
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url> 
        </license> 
    </licenses>  
    <!-- 开发者信息 -->  
    <developers> 
        <developer> 
            <name>Meng Wei Jin</name>  
            <email>aday.fun@outlook.com</email>
        </developer> 
    </developers>  
    <!--开源地址-->  
    <scm> 
        <url>https://github.com/mengweijin/vita</url>
    </scm>  
    <!--  Issue地址  -->  
    <issueManagement> 
        <system>Github Issue</system>
        <url>https://github.com/mengweijin/vita/issues</url>
    </issueManagement>  
    <build> 
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>io.github.linpeilie</groupId>
                            <artifactId>mapstruct-plus-processor</artifactId>
                            <version>${mapstruct-plus.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${lombok-mapstruct-binding.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <!-- 用来执行单元测试 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <!-- 是否跳过执行单元测试。 也可以配置 <properties> <skipTests>true</skipTests> </properties> 来实现。 -->
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin> 
                <groupId>org.apache.maven.plugins</groupId>  
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>  
            <!-- Javadoc -->  
            <plugin> 
                <groupId>org.apache.maven.plugins</groupId>  
                <artifactId>maven-javadoc-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!-- 禁用严格的文档检查 -->
                    <doclint>none</doclint>
                </configuration>
            </plugin>  
            <!-- GPG
                1. 需要安装 gpg4win-4.4.1.exe，并创建要给 OpenPGP 密钥对证书（邮箱填写中央仓库账号的邮箱），并右键【在服务器上发布】。
                2. 配置系统环境变量：MAVEN_GPG_PASSPHRASE=<证书的 passphrase>
            -->
            <plugin> 
                <groupId>org.apache.maven.plugins</groupId>  
                <artifactId>maven-gpg-plugin</artifactId>  
                <version>${maven-gpg-plugin.version}</version>
                <executions>
                    <execution>
                        <!-- 在 Maven 生命周期的 verify 阶段触发签名操作。该阶段位于 package 之后、install 之前，适合进行签名验证。 -->
                        <phase>verify</phase>
                        <goals>
                            <!-- 调用插件的 sign 目标，对已打包的 artifacts（如主 JAR、源码 JAR、POM 文件等）进行签名。 -->
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- 统一更新 pom.xml 中的版本 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <configuration>
                    <allowSnapshots>true</allowSnapshots>
                    <processAllModules>true</processAllModules>
                    <generateBackupPoms>false</generateBackupPoms>
                    <newVersion>2.0.0-M4</newVersion>
                </configuration>
            </plugin>
            <!-- 需要在 settings.xml 中配置 <server><id>central</id> ......其他配置 </server>           -->
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>${central-publishing-maven-plugin.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>central</publishingServerId>
                    <autoPublish>true</autoPublish>
                    <waitUntil>validated</waitUntil>
                </configuration>
            </plugin>
        </plugins> 
    </build>  

    <repositories>
        <repository>
            <id>snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
        </repository>
        <repository>
            <id>aliyun</id>
            <url>https://maven.aliyun.com/repository/public</url>
        </repository>
    </repositories>
    <pluginRepositories> 
        <pluginRepository>
            <id>aliyun</id>
            <url>https://maven.aliyun.com/repository/public</url>
        </pluginRepository> 
    </pluginRepositories> 
</project>
