/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/demo/iframe': RouteRecordInfo<
      '/demo/iframe',
      '/demo/iframe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/403': RouteRecordInfo<
      '/error/403',
      '/error/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/404': RouteRecordInfo<
      '/error/404',
      '/error/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/flow/warm/': RouteRecordInfo<
      '/flow/warm/',
      '/flow/warm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/cache-local/': RouteRecordInfo<
      '/monitor/cache-local/',
      '/monitor/cache-local',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/log-data-change/': RouteRecordInfo<
      '/monitor/log-data-change/',
      '/monitor/log-data-change',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/log-login/': RouteRecordInfo<
      '/monitor/log-login/',
      '/monitor/log-login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/log-operation/': RouteRecordInfo<
      '/monitor/log-operation/',
      '/monitor/log-operation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/log-system/': RouteRecordInfo<
      '/monitor/log-system/',
      '/monitor/log-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/scheduling/': RouteRecordInfo<
      '/monitor/scheduling/',
      '/monitor/scheduling',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/scheduling/[id]': RouteRecordInfo<
      '/monitor/scheduling/[id]',
      '/monitor/scheduling/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/monitor/server/': RouteRecordInfo<
      '/monitor/server/',
      '/monitor/server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/user-online/': RouteRecordInfo<
      '/monitor/user-online/',
      '/monitor/user-online',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/personal-information': RouteRecordInfo<
      '/profile/personal-information',
      '/profile/personal-information',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/category/': RouteRecordInfo<
      '/system/category/',
      '/system/category',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/config/': RouteRecordInfo<
      '/system/config/',
      '/system/config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dept/': RouteRecordInfo<
      '/system/dept/',
      '/system/dept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dict/': RouteRecordInfo<
      '/system/dict/',
      '/system/dict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dict/[dictTypeId]': RouteRecordInfo<
      '/system/dict/[dictTypeId]',
      '/system/dict/:dictTypeId',
      { dictTypeId: ParamValue<true> },
      { dictTypeId: ParamValue<false> },
      | never
    >,
    '/system/file/': RouteRecordInfo<
      '/system/file/',
      '/system/file',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/menu/': RouteRecordInfo<
      '/system/menu/',
      '/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/message/': RouteRecordInfo<
      '/system/message/',
      '/system/message',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/notice/': RouteRecordInfo<
      '/system/notice/',
      '/system/notice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/post/': RouteRecordInfo<
      '/system/post/',
      '/system/post',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role/': RouteRecordInfo<
      '/system/role/',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user/': RouteRecordInfo<
      '/system/user/',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tool/generator/': RouteRecordInfo<
      '/tool/generator/',
      '/tool/generator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tool/swagger-ui': RouteRecordInfo<
      '/tool/swagger-ui',
      '/tool/swagger-ui',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/demo/iframe.vue': {
      routes:
        | '/demo/iframe'
      views:
        | never
    }
    'src/pages/error/403.vue': {
      routes:
        | '/error/403'
      views:
        | never
    }
    'src/pages/error/404.vue': {
      routes:
        | '/error/404'
      views:
        | never
    }
    'src/pages/flow/warm/index.vue': {
      routes:
        | '/flow/warm/'
      views:
        | never
    }
    'src/pages/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/monitor/cache-local/index.vue': {
      routes:
        | '/monitor/cache-local/'
      views:
        | never
    }
    'src/pages/monitor/log-data-change/index.vue': {
      routes:
        | '/monitor/log-data-change/'
      views:
        | never
    }
    'src/pages/monitor/log-login/index.vue': {
      routes:
        | '/monitor/log-login/'
      views:
        | never
    }
    'src/pages/monitor/log-operation/index.vue': {
      routes:
        | '/monitor/log-operation/'
      views:
        | never
    }
    'src/pages/monitor/log-system/index.vue': {
      routes:
        | '/monitor/log-system/'
      views:
        | never
    }
    'src/pages/monitor/scheduling/index.vue': {
      routes:
        | '/monitor/scheduling/'
      views:
        | never
    }
    'src/pages/monitor/scheduling/[id].vue': {
      routes:
        | '/monitor/scheduling/[id]'
      views:
        | never
    }
    'src/pages/monitor/server/index.vue': {
      routes:
        | '/monitor/server/'
      views:
        | never
    }
    'src/pages/monitor/user-online/index.vue': {
      routes:
        | '/monitor/user-online/'
      views:
        | never
    }
    'src/pages/profile/personal-information.vue': {
      routes:
        | '/profile/personal-information'
      views:
        | never
    }
    'src/pages/system/category/index.vue': {
      routes:
        | '/system/category/'
      views:
        | never
    }
    'src/pages/system/config/index.vue': {
      routes:
        | '/system/config/'
      views:
        | never
    }
    'src/pages/system/dept/index.vue': {
      routes:
        | '/system/dept/'
      views:
        | never
    }
    'src/pages/system/dict/index.vue': {
      routes:
        | '/system/dict/'
      views:
        | never
    }
    'src/pages/system/dict/[dictTypeId].vue': {
      routes:
        | '/system/dict/[dictTypeId]'
      views:
        | never
    }
    'src/pages/system/file/index.vue': {
      routes:
        | '/system/file/'
      views:
        | never
    }
    'src/pages/system/menu/index.vue': {
      routes:
        | '/system/menu/'
      views:
        | never
    }
    'src/pages/system/message/index.vue': {
      routes:
        | '/system/message/'
      views:
        | never
    }
    'src/pages/system/notice/index.vue': {
      routes:
        | '/system/notice/'
      views:
        | never
    }
    'src/pages/system/post/index.vue': {
      routes:
        | '/system/post/'
      views:
        | never
    }
    'src/pages/system/role/index.vue': {
      routes:
        | '/system/role/'
      views:
        | never
    }
    'src/pages/system/user/index.vue': {
      routes:
        | '/system/user/'
      views:
        | never
    }
    'src/pages/tool/generator/index.vue': {
      routes:
        | '/tool/generator/'
      views:
        | never
    }
    'src/pages/tool/swagger-ui.vue': {
      routes:
        | '/tool/swagger-ui'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
