allowBuilds:
  "@scarf/scarf": true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - "@file-viewer/core@2.2.8"
  - "@file-viewer/doc@2.2.8"
  - "@file-viewer/eda-layout@2.2.8"
  - "@file-viewer/eda-orcad@2.2.8"
  - "@file-viewer/geometry-engine@2.2.8"
  - "@file-viewer/ppt@0.3.3"
  - "@file-viewer/pptx@2.2.8"
  - "@file-viewer/preset-all@2.2.8"
  - "@file-viewer/renderer-3d@2.2.8"
  - "@file-viewer/renderer-archive@2.2.8"
  - "@file-viewer/renderer-cad@2.2.8"
  - "@file-viewer/renderer-data@2.2.8"
  - "@file-viewer/renderer-drawing@2.2.8"
  - "@file-viewer/renderer-eda@2.2.8"
  - "@file-viewer/renderer-email@2.2.8"
  - "@file-viewer/renderer-epub@2.2.8"
  - "@file-viewer/renderer-geo@2.2.8"
  - "@file-viewer/renderer-image@2.2.8"
  - "@file-viewer/renderer-media@2.2.8"
  - "@file-viewer/renderer-mindmap@2.2.8"
  - "@file-viewer/renderer-ofd@2.2.8"
  - "@file-viewer/renderer-pdf@2.2.8"
  - "@file-viewer/renderer-presentation@2.2.8"
  - "@file-viewer/renderer-spreadsheet@2.2.8"
  - "@file-viewer/renderer-text@2.2.8"
  - "@file-viewer/renderer-typst@2.2.8"
  - "@file-viewer/renderer-word@2.2.8"
  - "@file-viewer/vite-plugin@2.2.8"
  - "@file-viewer/vue3@2.2.8"
  - globals@17.10.0
  - highlight.js@11.12.0
  - swagger-ui-dist@5.32.13
