info:
  app:
    parentGroupId: @project.parent.groupId@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
server:
  ssl:
    enabled: false
    # 服务端证书，单向认证
    key-store: classpath:mengweijin.jks
    # key-store: C:\Users\mengweijin\mengweijin.jks
    key-store-password: 123456
    key-store-type: JKS
    key-alias: mengweijin
    # 客户端证书认证，双向认证。可选值为：none、want 和 need
    client-auth: need
    # 这里也需要配置 mengweijin.jks 而不是 client.jks
    trust-store: classpath:mengweijin.jks
    trust-store-password: 123456
    trust-store-type: JKS
    trust-store-provider: SUN
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8720
