spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2/vitality;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
decorator:
  datasource:
    enabled: false
vitality:
  debug: false
knife4j:
  production: true
