export const columns = reactive({
	createByName: { label: "创建者", visible: false },
	createTime: { label: "创建时间", visible: false },
	disabled: { label: "状态", visible: true },
	icon: { label: "图标", visible: true },
	id: { label: "ID", visible: false },
	index: { label: "序号列", visible: false },
	operation: { label: "操作", visible: true },
	permission: { label: "权限字符", visible: true },
	selection: { label: "选择列", visible: false },
	seq: { label: "排序", visible: true },
	title: { label: "菜单标题", visible: true },
	type: { label: "菜单类型", visible: true },
	updateByName: { label: "更新者", visible: false },
	updateTime: { label: "更新时间", visible: false },
	url: { label: "路由路径/URL", visible: true },
});
