spring:
  jpa:
    # spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering.
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

