info:
  app:
    parentGroupId: @project.parent.groupId@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.188.133:5236?schema=TEST&compatibleMode=oracle
    username: TEST
    password: 123456789
  flyway:
    # 默认不启用，true 为启用
    enabled: false
# flowable 配置
flowable:
  process:
    servlet:
      path: /flow
  common:
    app:
      idmUrl: /
  async-executor-activate: false #关闭定时任务JOB
  database-schema-update: true # 数据库表迁移，true 会自动创建表。
  modeler:
    app:
      deploymentApiUrl: /flow/app