info:
  app:
    parentGroupId: @project.parent.groupId@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
server:
  servlet:
    context-path: /flow-ui
spring:
  flyway:
    # 默认不启用，true 为启用
    enabled: false
# flowable 配置。UI：http://localhost:8080/
flowable:
  idm:
    app:
      admin:
        user-id: admin
        password: 123456
        first-name: Test
        last-name: Administrator
        email: mengweijin.work@foxmail.com
  #database-schema-update: true # 数据库表迁移，true 会自动创建表。
