const columns = reactive({
  selection: { label: "选择列", visible: false },
  index: { label: "序号列", visible: false },
  id: { label: "ID", visible: false },
  flowCode: { label: "流程编码", visible: true },
  flowName: { label: "流程名称", visible: true },
  modelValue: { label: "设计器模型", visible: true },
  category: { label: "流程分类ID", visible: false },
  categoryName: { label: "流程分类", visible: true },
  version: { label: "流程版本", visible: true },
  isPublish: { label: "是否发布", visible: true },
  formCustom: { label: "表单是否自定义", visible: false },
  formPath: { label: "表单路径", visible: false },
  activityStatus: { label: "激活状态", visible: true },
  listenerType: { label: "监听器类型", visible: false },
  listenerPath: { label: "监听器路径", visible: false },
  ext: { label: "扩展字段", visible: false },
  delFlag: { label: "删除标记", visible: false },
  tenantId: { label: "租户ID", visible: false },
  createByName: { label: "创建者", visible: false },
  createTime: { label: "创建时间", visible: false },
  updateByName: { label: "更新者", visible: false },
  updateTime: { label: "更新时间", visible: false },
  operation: { label: "操作", visible: true },
});

export { columns };
