# For more information, see:
# Docs: https://docs.github.com/zh/actions
# Marketplace: https://github.com/marketplace?type=actions
name: Close Stale Issues and PRs

on:
  schedule:
    - cron: "0 0 * * 0"           # 每周日 00:00 UTC 执行（即每7天一次）
      timezone: "Asia/Shanghai"   # 指定为北京时间

jobs:
  issue-stale-close:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v11
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 7
          stale-issue-message: 'This issue is stale because it has been open for many days with no activity.'
          close-issue-message: 'This issue was closed because it has been inactive for many days since being marked as stale.'
